// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingReservation.Infrastructure.Data;

#nullable disable

namespace ParkingReservation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805190254_UpdateSeedDataWith100Spaces")]
    partial class UpdateSeedDataWith100Spaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingReservation.Domain.Entities.ParkingSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            Type = 0
                        },
                        new
                        {
                            Id = 41,
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            Type = 0
                        },
                        new
                        {
                            Id = 44,
                            Type = 0
                        },
                        new
                        {
                            Id = 45,
                            Type = 0
                        },
                        new
                        {
                            Id = 46,
                            Type = 0
                        },
                        new
                        {
                            Id = 47,
                            Type = 0
                        },
                        new
                        {
                            Id = 48,
                            Type = 0
                        },
                        new
                        {
                            Id = 49,
                            Type = 0
                        },
                        new
                        {
                            Id = 50,
                            Type = 0
                        },
                        new
                        {
                            Id = 51,
                            Type = 0
                        },
                        new
                        {
                            Id = 52,
                            Type = 0
                        },
                        new
                        {
                            Id = 53,
                            Type = 0
                        },
                        new
                        {
                            Id = 54,
                            Type = 0
                        },
                        new
                        {
                            Id = 55,
                            Type = 0
                        },
                        new
                        {
                            Id = 56,
                            Type = 0
                        },
                        new
                        {
                            Id = 57,
                            Type = 0
                        },
                        new
                        {
                            Id = 58,
                            Type = 0
                        },
                        new
                        {
                            Id = 59,
                            Type = 0
                        },
                        new
                        {
                            Id = 60,
                            Type = 0
                        },
                        new
                        {
                            Id = 61,
                            Type = 0
                        },
                        new
                        {
                            Id = 62,
                            Type = 0
                        },
                        new
                        {
                            Id = 63,
                            Type = 0
                        },
                        new
                        {
                            Id = 64,
                            Type = 0
                        },
                        new
                        {
                            Id = 65,
                            Type = 0
                        },
                        new
                        {
                            Id = 66,
                            Type = 0
                        },
                        new
                        {
                            Id = 67,
                            Type = 0
                        },
                        new
                        {
                            Id = 68,
                            Type = 0
                        },
                        new
                        {
                            Id = 69,
                            Type = 0
                        },
                        new
                        {
                            Id = 70,
                            Type = 0
                        },
                        new
                        {
                            Id = 71,
                            Type = 0
                        },
                        new
                        {
                            Id = 72,
                            Type = 0
                        },
                        new
                        {
                            Id = 73,
                            Type = 0
                        },
                        new
                        {
                            Id = 74,
                            Type = 0
                        },
                        new
                        {
                            Id = 75,
                            Type = 0
                        },
                        new
                        {
                            Id = 76,
                            Type = 0
                        },
                        new
                        {
                            Id = 77,
                            Type = 0
                        },
                        new
                        {
                            Id = 78,
                            Type = 0
                        },
                        new
                        {
                            Id = 79,
                            Type = 0
                        },
                        new
                        {
                            Id = 80,
                            Type = 0
                        },
                        new
                        {
                            Id = 81,
                            Type = 1
                        },
                        new
                        {
                            Id = 82,
                            Type = 1
                        },
                        new
                        {
                            Id = 83,
                            Type = 1
                        },
                        new
                        {
                            Id = 84,
                            Type = 1
                        },
                        new
                        {
                            Id = 85,
                            Type = 1
                        },
                        new
                        {
                            Id = 86,
                            Type = 1
                        },
                        new
                        {
                            Id = 87,
                            Type = 1
                        },
                        new
                        {
                            Id = 88,
                            Type = 1
                        },
                        new
                        {
                            Id = 89,
                            Type = 1
                        },
                        new
                        {
                            Id = 90,
                            Type = 1
                        },
                        new
                        {
                            Id = 91,
                            Type = 2
                        },
                        new
                        {
                            Id = 92,
                            Type = 2
                        },
                        new
                        {
                            Id = 93,
                            Type = 2
                        },
                        new
                        {
                            Id = 94,
                            Type = 2
                        },
                        new
                        {
                            Id = 95,
                            Type = 2
                        },
                        new
                        {
                            Id = 96,
                            Type = 2
                        },
                        new
                        {
                            Id = 97,
                            Type = 2
                        },
                        new
                        {
                            Id = 98,
                            Type = 2
                        },
                        new
                        {
                            Id = 99,
                            Type = 2
                        },
                        new
                        {
                            Id = 100,
                            Type = 2
                        });
                });

            modelBuilder.Entity("ParkingReservation.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ParkingSpaceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpaceId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicantName = "Teszt Felhasználó 1",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 11, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 1,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 11, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            ApplicantName = "Teszt Felhasználó 2",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 2,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            ApplicantName = "Teszt Felhasználó 3",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 13, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 3,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 13, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            ApplicantName = "Teszt Felhasználó 4",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 14, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 4,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            ApplicantName = "Teszt Felhasználó 5",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 5,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            ApplicantName = "Teszt Felhasználó 6",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 16, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 6,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            ApplicantName = "Teszt Felhasználó 7",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 17, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 7,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            ApplicantName = "Teszt Felhasználó 8",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 18, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 8,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            ApplicantName = "Teszt Felhasználó 9",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 19, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 9,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 19, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            ApplicantName = "Teszt Felhasználó 10",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 10, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 10,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 10, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            ApplicantName = "Teszt Felhasználó 11",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 11, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 11,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 11, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            ApplicantName = "Teszt Felhasználó 12",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 12,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            ApplicantName = "Teszt Felhasználó 13",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 13, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 13,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 13, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            ApplicantName = "Teszt Felhasználó 14",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 14, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 14,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 15,
                            ApplicantName = "Teszt Felhasználó 15",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 15,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 16,
                            ApplicantName = "Teszt Felhasználó 16",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 16, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 16,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 17,
                            ApplicantName = "Teszt Felhasználó 17",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 17, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 17,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 18,
                            ApplicantName = "Teszt Felhasználó 18",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 18, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 18,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 19,
                            ApplicantName = "Teszt Felhasználó 19",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 19, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 19,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 19, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 20,
                            ApplicantName = "Teszt Felhasználó 20",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 10, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 20,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 10, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 21,
                            ApplicantName = "Teszt Felhasználó 21",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 11, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 21,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 11, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 22,
                            ApplicantName = "Teszt Felhasználó 22",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 22,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 23,
                            ApplicantName = "Teszt Felhasználó 23",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 13, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 23,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 13, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 24,
                            ApplicantName = "Teszt Felhasználó 24",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 14, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 24,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 25,
                            ApplicantName = "Teszt Felhasználó 25",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 25,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 26,
                            ApplicantName = "Teszt Felhasználó 26",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 16, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 26,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 27,
                            ApplicantName = "Teszt Felhasználó 27",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 17, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 27,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 28,
                            ApplicantName = "Teszt Felhasználó 28",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 18, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 28,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 29,
                            ApplicantName = "Teszt Felhasználó 29",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 19, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 29,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 19, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 30,
                            ApplicantName = "Teszt Felhasználó 30",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 10, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 30,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 10, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 31,
                            ApplicantName = "Teszt Felhasználó 31",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 11, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 31,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 11, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 32,
                            ApplicantName = "Teszt Felhasználó 32",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 32,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 33,
                            ApplicantName = "Teszt Felhasználó 33",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 13, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 33,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 13, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 34,
                            ApplicantName = "Teszt Felhasználó 34",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 14, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 34,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 35,
                            ApplicantName = "Teszt Felhasználó 35",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 35,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 36,
                            ApplicantName = "Teszt Felhasználó 36",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 16, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 36,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 37,
                            ApplicantName = "Teszt Felhasználó 37",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 17, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 37,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 38,
                            ApplicantName = "Teszt Felhasználó 38",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 18, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 38,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 39,
                            ApplicantName = "Teszt Felhasználó 39",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 19, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 39,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 19, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 40,
                            ApplicantName = "Teszt Felhasználó 40",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 10, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 40,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 10, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 41,
                            ApplicantName = "Teszt Felhasználó 41",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 11, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 41,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 11, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 42,
                            ApplicantName = "Teszt Felhasználó 42",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 42,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 43,
                            ApplicantName = "Teszt Felhasználó 43",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 13, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 43,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 13, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 44,
                            ApplicantName = "Teszt Felhasználó 44",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 14, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 44,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 45,
                            ApplicantName = "Teszt Felhasználó 45",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 45,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 15, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 46,
                            ApplicantName = "Teszt Felhasználó 46",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 16, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 46,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 47,
                            ApplicantName = "Teszt Felhasználó 47",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 17, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 47,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 48,
                            ApplicantName = "Teszt Felhasználó 48",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 18, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 48,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 49,
                            ApplicantName = "Teszt Felhasználó 49",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 19, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 49,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 19, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Id = 50,
                            ApplicantName = "Teszt Felhasználó 50",
                            EndTime = new DateTimeOffset(new DateTime(2026, 8, 10, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            ParkingSpaceId = 50,
                            StartTime = new DateTimeOffset(new DateTime(2026, 8, 10, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ParkingReservation.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("ParkingReservation.Domain.Entities.ParkingSpace", "ParkingSpace")
                        .WithMany("Reservations")
                        .HasForeignKey("ParkingSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingSpace");
                });

            modelBuilder.Entity("ParkingReservation.Domain.Entities.ParkingSpace", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
